### ISSUE TITLE
Undefined or exception is returned when using QuickJSValue.Call to call the constructor

### ISSUE THREAD

**Issue by vovgou** [vmas/QuickJS.NET#3]
JS code（test.js）：

function Person(name) {
    this.name = name
    this.sayName = function () {
        return this.name
    }
}
Person.prototype.cry = function () {
    print('cry')
}
var person1 = new Person('clark')
person1.cry()
---------------------------------
C# code：

QuickJSValue global = context.GetGlobal();
global.DefineFunction("print", Print, 1, JSPropertyFlags.CWE);
JSContext ctx = context.NativeInstance;
context.EvalFile("./test.js", Encoding.UTF8, JSEvalFlags.Global);

//example 1:Call the constructor "Person(name)"
QuickJSValue person = (QuickJSValue)global.GetProperty("Person");
object clark = person.Call(null, JSValue.Create(ctx, "Clark")); // the result is undefined.
Console.WriteLine("{0}", clark); //  result: undefined

//example2:Call the constructor "Proxy(target,handler)"
QuickJSValue target = QuickJSValue.Create(context);
QuickJSValue handler = QuickJSValue.Create(context);
JSCFunction handle = (ctx, this_val, argc, argv) =>
{
	return JSValue.Undefined;
};
handler.DefineFunction("get", handle, 3, JSPropertyFlags.CWE);
object proxyObj = proxy.Call(null, target.NativeInstance, handler.NativeInstance); //This result is an exception, the content of it is "must be called with new".

Did I use this method incorrectly? what should I do? 
Thank you！

**Comment by vmas** [comment]
I think JS_CallConstructor/JS_CallConstructor2 should be called. This functionality has not yet been implemented in the QuickJSValue class.

**Comment by vovgou** [comment]
> I think JS_CallConstructor/JS_CallConstructor2 should be called. This functionality has not yet been implemented in the QuickJSValue class.

I tried to use these two functions to call them, but failed, and my application crashed.

**Comment by vmas** [comment]
This code works for me:
```
QuickJSValue global = context.GetGlobal();
QuickJSValue person = (QuickJSValue)global.GetProperty("Person");
QuickJSValue clark = person.CallConstructor();
//JSValue clarkValue = JS_CallConstructor(context.NativeInstance, person.NativeInstance, 1, new JSValue[] { JSValue.Create(context.NativeInstance, "Clark") });
//QuickJSValue clark = QuickJSValue.Wrap(context, clarkValue);
Console.WriteLine("{0}", clark);
((QuickJSValue)clark.GetProperty("cry")).Call();

//example2:Call the constructor "Proxy(target,handler)"
QuickJSValue target = QuickJSValue.Create(context);
QuickJSValue handler = QuickJSValue.Create(context);
JSCFunction handle = (ctx, this_val, argc, argv) =>
{
	return JSValue.Undefined;
};
handler.DefineFunction("get", handle, 3, JSPropertyFlags.CWE);
var proxy = (QuickJSValue)global.GetProperty("Proxy");
object proxyObj = proxy.CallConstructor(target.NativeInstance, handler.NativeInstance); //This result is an exception, the content of it is "must be called with new".

GC.KeepAlive(target);
GC.KeepAlive(proxy);
GC.KeepAlive(handler);
```

**Comment by vovgou** [comment]
Yes, it works!

// The following code will crash
QuickJSValue person = (QuickJSValue)global.GetProperty("Person");
JSValue p = JS_CallConstructor(ctx, person.NativeInstance, 1, new JSValue[] { JSValue.Create(ctx, "Clark") });

//After I added a line of code, it worked great!I checked the code of the Wrap function, it should be that the object was released causing the crash.
QuickJSValue p2 = QuickJSValue.Wrap(context,p);					

Thanks!!
