### ISSUE TITLE
Why use Utils.StringToManagedUTF8 to marshal the property name.I don’t understand it, could you tell me？

### ISSUE THREAD

**Issue by vovgou** [vmas/QuickJS.NET#4]
Why use Utils.StringToManagedUTF8 to marshal the property name? It requires memory to be allocated on the heap, why not use the default marshaling method [MarshalAs(UnmanagedType.LPStr)]? I don’t understand it, could you tell me？thank you！

When using Utils.StringToManagedUTF8 to marshal the property name, if it is called in Unity's Update method, there will be GC in every frame,and there will be no GC when using the default marshaling method.

![image](https://user-images.githubusercontent.com/2171221/95540329-1e18b180-0a23-11eb-869b-5a54590538c2.png)

**Comment by vmas** [comment]
ECMAScript allows Unicode for property names. QuickJS supports the UTF-8/CESU-8. So, the marshaling from and to an LPStr is only valid for the ASCII-7 range.

**Comment by vovgou** [comment]
When I use LPStr, I try to use Japanese, Korean, Lao, Thai, etc. as property names, and they all work well.It seems that Utils.StringToManagedUTF8 can not be used, maybe I am missing something?

**Comment by vmas** [comment]
This code does not working:
```
QuickJSValue glob = context.GetGlobal();
JS_SetPropertyStr(context.NativeInstance, glob.NativeInstance, "ёжик", JSValue.Create(1));	
GC.KeepAlive(glob);
context.Eval("print('this.ёжик = ' + this.ёжик)", "file.js", JSEvalFlags.Global);
```

This code works:
```
QuickJSValue glob = context.GetGlobal();
glob.SetProperty("ёжик", 1);
context.Eval("print('this.ёжик = ' + this.ёжик)", "file.js", JSEvalFlags.Global);
```

**Comment by vovgou** [comment]
Yes, I know the reason. It is normal for me to execute the code in Unity3D. Maybe it uses UTF8 encoding by default. I tested it in the C# project and the system default encoding GBK was used, and an error would be reported. thank you！

**Comment by vovgou** [comment]
I tried to use Marshal.StringToCoTaskMemAnsi() to marshal a Japanese string, which worked in Unity3D, but failed to call in a C# project.It is possible that Unity3D modified the code of mono, thank you！

byte* aName = (byte*)Marshal.StringToCoTaskMemAnsi(name);
int rv = JS_SetPropertyStr(context.NativeInstance, obj.NativeInstance, aName, JSValue.Create(context.NativeInstance, value));
if (rv == -1)
	context.NativeInstance.ThrowPendingException();
return rv == 1;
